from BaseClasses import Location

base_location_id = 3300000


class THPS3Location(Location):
    game: str = "THPS3"

class LocationData:
	def __init__(self, region, name, location_id)
		self.region: str = region
		self.name: str = name
		self.short_location_id: int = location_id
		self.location_id: int = location_id + base_location_id

location_table = {
		#Foundry level 00
	"Foundry High Score": LocationData("Foundry", "Foundry High Score", 0x10),
	"Foundry Pro Score": LocationData("Foundry", "Foundry Pro Score", 0x11),
	"Foundry Sick Score": LocationData("Foundry", "Foundry Sick Score", 0x12),
	"Foundry SKATE": LocationData("Foundry", "Foundry SKATE", 0x13),
	"Foundry Valves": LocationData("Foundry", "Foundry Valves", 0x14),
	"Foundry Press": LocationData("FoundryGrind", "Foundry Press", 0x15),
	"Foundry Cannonball Over Halfpipe": LocationData("FoundryCannonball", "Foundry Cannonball Over Halfpipe", 0x16),
	"Foundry Control Booth": LocationData("FoundryGrind", "Foundry Control Booth", 0x17),
	"Foundry Secret Tape": LocationData("Foundry", "Foundry Secret Tape", 0x18),
	"Foundry 100 Percent": LocationData("FoundryFinal", "Foundry 100 Percent", 0x19),
	"Foundry SP Press": LocationData("Foundry", "Foundry SP Press", 0x1A),
	"Foundry SP Catwalk": LocationData("Foundry", "Foundry SP Catwalk", 0x1B),
	"Foundry SP Back Balcony": LocationData("Foundry", "Foundry SP Back Balcony", 0x1C),
	"Foundry SP Right Pipe": LocationData("Foundry", "Foundry SP Right Pipe", 0x1D),
	"Foundry SP Back Door": LocationData("Foundry", "Foundry SP Back Door", 0x1E),
	"Foundry Deck": LocationData("Foundry", "Foundry Deck", 0x1F),
		#Los Angeles level 01
	"LA High Score": LocationData("LA", "LA High Score", 0x20),
	"LA Pro Score": LocationData("LA", "LA Pro Score", 0x21),
	"LA Sick Score": LocationData("LA", "LA Sick Score", 0x22),
	"LA SKATE": LocationData("LA", "LA SKATE", 0x23),
	"LA Transformers": LocationData("LA", "LA Transformers", 0x24),
	"LA Electric Rail": LocationData("LAGrind", "LA Electric Rail", 0x25),
	"LA Elevator Grind": LocationData("LAGrind", "LA Elevator Grind", 0x26),
	"LA Kickflip Over Lobby": LocationData("LAKickflip", "LA Kickflip Over Lobby", 0x27),
	"LA Secret Tape": LocationData("LA", "LA Secret Tape", 0x28),
	"LA 100 Percent": LocationData("LAFinal", "LA 100 Percent", 0x29),
	"LA SP Park Powerline": LocationData("LA", "LA SP Park Powerline", 0x2A),
	"LA SP Highway": LocationData("LA", "LA SP Highway", 0x2B),
	"LA SP Theater": LocationData("LA", "LA SP Theater", 0x2C),
	"LA SP Building Powerline": LocationData("LA", "LA SP Building Powerline", 0x2D),
	"LA SP Graffiti Powerline": LocationData("LA", "LA SP Graffiti Powerline", 0x2E),
	"LA Deck": LocationData("LA", "LA Deck", 0x2F),
		#Rio de Janeiro level 02
	"Rio Medal": LocationData("Rio", "Rio Medal", 0x30),
	#"Rio Silver": LocationData("Rio", "Rio Silver", 0x31),
	#"Rio Gold": LocationData("Rio", "Rio Gold", 0x32),
	"Rio SP Behind Quicksilver": LocationData("Rio", "Rio SP Behind Quicksilver", 0x3A),
	"Rio SP Quicksilver Vert": LocationData("Rio", "Rio SP Quicksilver Vert", 0x3B),
	"Rio SP Wood Vert Powerline": LocationData("Rio", "Rio SP Wood Vert Powerline", 0x3C),
	"Rio SP Alley": LocationData("Rio", "Rio SP Alley", 0x3D),
	"Rio SP Balcony": LocationData("Rio", "Rio SP Balcony", 0x3E),
	"Rio Deck": LocationData("Rio", "Rio Deck", 0x3F),
		#Suburbia level 03
	"Suburbia High Score": LocationData("Suburbia", "Suburbia High Score", 0x40),
	"Suburbia Pro Score": LocationData("Suburbia", "Suburbia Pro Score", 0x41),
	"Suburbia Sick Score": LocationData("Suburbia", "Suburbia Sick Score", 0x42),
	"Suburbia SKATE": LocationData("Suburbia", "Suburbia SKATE", 0x43),
	"Suburbia Appliances": LocationData("Suburbia", "Suburbia Appliances", 0x44),
	"Suburbia Dishes": LocationData("Suburbia", "Suburbia Dishes", 0x45),
	"Suburbia Ice Cream Man": LocationData("Suburbia", "Suburbia Ice Cream Man", 0x46),
	"Suburbia 360 Flip The Weathervane": LocationData("Suburbia360Flip", "Suburbia 360 Flip The Weathervane", 0x47),
	"Suburbia Secret Tape": LocationData("Suburbia", "Suburbia Secret Tape", 0x48),
	"Suburbia 100 Percent": LocationData("SuburbiaFinal", "Suburbia 100 Percent", 0x49),
	"Suburbia SP Small House": LocationData("Suburbia", "Suburbia SP Small House", 0x4A),
	"Suburbia SP Powerline": LocationData("Suburbia", "Suburbia SP Powerline", 0x4B),
	"Suburbia SP Above Mobile Home": LocationData("Suburbia", "Suburbia SP Above Mobile Home", 0x4C),
	"Suburbia SP Big House": LocationData("Suburbia", "Suburbia SP Big House", 0x4D),
	"Suburbia SP Mobile Home": LocationData("Suburbia", "Suburbia SP Mobile Home", 0x4E),
	"Suburbia Deck": LocationData("Suburbia", "Suburbia Deck", 0x4F),
		#Airport 04
	"Airport High Score": LocationData("Airport", "Airport High Score", 0x50),
	"Airport Pro Score": LocationData("Airport", "Airport Pro Score", 0x51),
	"Airport Sick Score": LocationData("Airport", "Airport Sick Score", 0x52),
	"Airport SKATE": LocationData("Airport", "Airport SKATE", 0x53),
	"Airport Flags": LocationData("AirportGrind", "Airport Flags", 0x54),
	"Airport Lost Luggage": LocationData("Airport", "Airport Lost Luggage", 0x55),
	"Airport Nosebluntslide Sign": LocationData("AirportNosebluntslide", "Airport Nosebluntslide Sign", 0x56),
	"Airport Grind The Plane": LocationData("AirportGrind", "Airport Grind The Plane", 0x57),
	"Airport Secret Tape": LocationData("Airport", "Airport Secret Tape", 0x58),
	"Airport 100 Percent": LocationData("AirportFinal", "Airport 100 Percent", 0x59),
	"Airport SP Light": LocationData("Airport", "Airport SP Light", 0x5A),
	"Airport SP Escalator Light": LocationData("Airport", "Airport SP Escalator Light", 0x5B),
	"Airport SP Metal Detector": LocationData("Airport", "Airport SP Metal Detector", 0x5C),
	"Airport SP Sign": LocationData("Airport", "Airport SP Sign", 0x5D), #need better name
	"Airport SP Rail": LocationData("Airport", "Airport SP Rail", 0x5E),
	"Airport Deck": LocationData("Airport", "Airport Deck", 0x5F),
		#Skater Island level 05
	"Skater Island Medal": LocationData("Skater Island", "Skater Island Medal", 0x60),
	#"Skater Island Silver": LocationData("Skater Island", "Skater Island Silver", 0x61),
	#"Skater Island Gold": LocationData("Skater Island", "Skater Island Gold", 0x62),
	"Skater Island SP Doorway Gap": LocationData("Skater Island", "Skater Island SP Doorway Gap", 0x6A),
	"Skater Island SP Halfpipe": LocationData("Skater Island", "Skater Island SP Halfpipe", 0x6B),
	"Skater Island SP Doorway Rail": LocationData("Skater Island", "Skater Island SP Doorway Rail", 0x6C),
	"Skater Island SP THPS3 Sign": LocationData("Skater Island", "Skater Island SP THPS3 Sign", 0x6D),
	"Skater Island SP Pool": LocationData("Skater Island", "Skater Island SP Pool", 0x6E),
	"Skater Island Deck": LocationData("Skater Island", "Skater Island Deck", 0x6F),
		#Canada 06
	"Canada High Score": LocationData("Canada", "Canada High Score", 0x70),
	"Canada Pro Score": LocationData("Canada", "Canada Pro Score", 0x71),
	"Canada Sick Score": LocationData("Canada", "Canada Sick Score", 0x72),
	"Canada SKATE": LocationData("Canada", "Canada SKATE", 0x73),
	"Canada Totem Poles": LocationData("Canada", "Canada Totem Poles", 0x74),
	"Canada Blow Up Tree": LocationData("Canada", "Canada Blow Up Tree", 0x75),
	"Canada Nosegrind Tree": LocationData("CanadaNosegrind", "Canada Nosegrind Tree", 0x76),
	"Canada Ollie Over Pool": LocationData("Canada", "Canada Ollie Over Pool", 0x77),
	"Canada Secret Tape": LocationData("Canada", "Canada Secret Tape", 0x78),
	"Canada 100 Percent": LocationData("CanadaFinal", "Canada 100 Percent", 0x79),
	"Canada SP Rooftop": LocationData("Canada", "Canada SP Rooftop", 0x7A),
	"Canada SP Banner": LocationData("Canada", "Canada SP Banner", 0x7B),
	"Canada SP Train Tracks": LocationData("Canada", "Canada SP Train Tracks", 0x7C),
	"Canada SP Park Rail": LocationData("Canada", "Canada SP Park Rail", 0x7D), 
	"Canada SP Ramp": LocationData("Canada", "Canada SP Ramp", 0x7E),
	"Canada Deck": LocationData("Canada", "Canada Deck", 0x7F),
		#Tokyo level 07
	"Tokyo Medal": LocationData("Tokyo", "Tokyo Medal", 0x80),
	#"Tokyo Silver": LocationData("Tokyo", "Tokyo Silver", 0x81),
	#"Tokyo Gold": LocationData("Tokyo", "Tokyo Gold", 0x82),
	"Tokyo SP Glass": LocationData("Tokyo", "Tokyo SP Glass", 0x8A),
	"Tokyo SP Left Vert": LocationData("Tokyo", "Tokyo SP Left Vert", 0x8B),
	"Tokyo SP Bridge": LocationData("Tokyo", "Tokyo SP Bridge", 0x8C),
	"Tokyo SP Hologram": LocationData("Tokyo", "Tokyo SP Hologram", 0x8D),
	"Tokyo SP Right Rail": LocationData("Tokyo", "Tokyo SP Right Rail", 0x8E),
	"All Goals and Medals": LocationData("AllFinal", "All Goals and Medals", 0x8F),
		#Downhill level 08
	"Downhill SP Trees": LocationData("Downhill", "Downhill SP Trees", 0x90),
	"Downhill SP Grind 1": LocationData("Downhill", "Downhill SP Grind 1", 0x91),
	"Downhill SP Grind 2": LocationData("Downhill", "Downhill SP Grind 2", 0x92),
	"Downhill SP Grind 3": LocationData("Downhill", "Downhill SP Grind 3", 0x93),
	"Downhill SP Grind 4": LocationData("Downhill", "Downhill SP Grind 4", 0x94),
	"Downhill SP Grind 5": LocationData("Downhill", "Downhill SP Grind 5", 0x95),
	"Downhill SP Grind 6": LocationData("Downhill", "Downhill SP Grind 6", 0x96),
	"Downhill SP Grind 7": LocationData("Downhill", "Downhill SP Grind 7", 0x97),
	"Downhill SP Grind 8": LocationData("Downhill", "Downhill SP Grind 8", 0x98),
	"Downhill SP Grind 9": LocationData("Downhill", "Downhill SP Grind 9", 0x99),
        #Foundry Gaps
    "Foundry Over The Halfpipe": LocationData("FoundryGaps", "Foundry Over The Halfpipe", 0xA0),
    "Foundry Perfect Gap": LocationData("FoundryGaps", "Foundry Perfect Gap", 0xA1),
    "Foundry Second Story Air": LocationData("FoundryGaps", "Foundry Second Story Air", 0xA2),
    "Foundry Channel Surfin": LocationData("FoundryGaps", "Foundry Channel Surfin", 0xA3),
    "Foundry Clear The Roller": LocationData("FoundryGaps", "Foundry Clear The Roller", 0xA4),
    "Foundry Over The Flat": LocationData("FoundryGaps", "Foundry Over The Flat", 0xA5),
    "Foundry What Are You Doing Here": LocationData("FoundryGaps", "Foundry What Are You Doing Here", 0xA6),
    "Foundry Southside Air": LocationData("FoundryGaps", "Foundry Southside Air", 0xA7),
    "Foundry Wedge Gap": LocationData("FoundryGaps", "Foundry Wedge Gap", 0xA8),
    "Foundry Over The Hard Way": LocationData("FoundryGaps", "Foundry Over The Hard Way", 0xA9),
    "Foundry Skillz Gap": LocationData("FoundryGaps", "Foundry Skillz Gap", 0xAA),
    "Foundry Bubblin Brew": LocationData("FoundryGaps", "Foundry Bubblin Brew", 0xAB),
    "Foundry High To Low": LocationData("FoundryGaps", "Foundry High To Low", 0xAC),
    "Foundry Death Gap East": LocationData("FoundryGaps", "Foundry Death Gap East", 0xAD),
    "Foundry Death Gap West": LocationData("FoundryGaps", "Foundry Death Gap West", 0xAE),
    "Foundry Gapman And Robin": LocationData("FoundryGaps", "Foundry Gapman And Robin", 0xAF),
    "Foundry Getting Higher": LocationData("FoundryGaps", "Foundry Getting Higher", 0xB0),
    "Foundry Knock The Bucket": LocationData("FoundryGaps", "Foundry Knock The Bucket", 0xB1),
    "Foundry Pipe-Hoppin' Grinder": LocationData("FoundryGaps", "Foundry Pipe-Hoppin' Grinder", 0xB2),
    "Foundry Grind The Gap": LocationData("FoundryGaps", "Foundry Grind The Gap", 0xB3),
    "Foundry Along The Handrail": LocationData("FoundryGaps", "Foundry Along The Handrail", 0xB4),
    "Foundry Grind Away": LocationData("FoundryGaps", "Foundry Grind Away", 0xB5),
    "Foundry Pipe Grind": LocationData("FoundryGaps", "Foundry Pipe Grind", 0xB6),
    "Foundry High Ledge Grind": LocationData("FoundryGaps", "Foundry High Ledge Grind", 0xB7),
    "Foundry Board Burner": LocationData("FoundryGaps", "Foundry Board Burner", 0xB8),
    "Foundry End To End": LocationData("FoundryGaps", "Foundry End To End", 0xB9),
    "Foundry Going Forward": LocationData("FoundryGaps", "Foundry Going Forward", 0xBA),
    "Foundry Comby Bear Style": LocationData("FoundryGaps", "Foundry Comby Bear Style", 0xBB),
    "Foundry Phat Ledge": LocationData("FoundryGaps", "Foundry Phat Ledge", 0xBC),
    "Foundry Workers Union": LocationData("FoundryGaps", "Foundry Workers Union", 0xBD),
    "Foundry To The D-Tank": LocationData("FoundryGaps", "Foundry To The D-Tank", 0xBE),
    "Foundry Go The Distance": LocationData("FoundryGaps", "Foundry Go The Distance", 0xBF),
    "Foundry Catwalk Crawler": LocationData("FoundryGaps", "Foundry Catwalk Crawler", 0xC0),
    "Foundry Triple Beam": LocationData("FoundryGaps", "Foundry Triple Beam", 0xC1),
    "Foundry Steppin' Up": LocationData("FoundryGaps", "Foundry Steppin' Up", 0xC2),
    "Foundry Tight-Pipe Grinder": LocationData("FoundryGaps", "Foundry Tight-Pipe Grinder", 0xC3),
    "Foundry Eastside Rail Hoppin'": LocationData("FoundryGaps", "Foundry Eastside Rail Hoppin'", 0xC4),
    "Foundry Westside Rail Hoppin'": LocationData("FoundryGaps", "Foundry Westside Rail Hoppin'", 0xC5),
    "Foundry Criss-Crossed": LocationData("FoundryGaps", "Foundry Criss-Crossed", 0xC6),
    "Foundry Nice": LocationData("FoundryGaps", "Foundry Nice", 0xC7),
    "Foundry Booya Gramma... Booya": LocationData("FoundryGaps", "Foundry Booya Gramma... Booya", 0xC8),
    "Foundry Gettin' Over": LocationData("FoundryGaps", "Foundry Gettin' Over", 0xC9),
    "Foundry The Proof Is In The Gap": LocationData("FoundryGaps", "Foundry The Proof Is In The Gap", 0xCA),
    "Foundry Drop And Grind": LocationData("FoundryGaps", "Foundry Drop And Grind", 0xCB),
    "Foundry Tight!": LocationData("FoundryGaps", "Foundry Tight!", 0xCC),
    "Foundry Shaba Style": LocationData("FoundryGaps", "Foundry Shaba Style", 0xCD),
    "Foundry Proball": LocationData("FoundryGaps", "Foundry Proball", 0xCE),
    "Foundry Saved By The Grind": LocationData("FoundryGaps", "Foundry Saved By The Grind", 0xCF),
    "Foundry World According To Gap": LocationData("FoundryGaps", "Foundry World According To Gap", 0xD0),
    "Foundry We Work Hard": LocationData("FoundryGaps", "Foundry We Work Hard", 0xD1),
    "Foundry We Play Hard": LocationData("FoundryGaps", "Foundry We Play Hard", 0xD2),
    "Foundry Sweat": LocationData("FoundryGaps", "Foundry Sweat", 0xD3),
        #LA Gaps
    "LA Flyin High!": LocationData("LAGaps", "LA Flyin High!", 0xD4),
    "LA Carwash": LocationData("LAGaps", "LA Carwash", 0xD5),
    "LA Wrath Of God!": LocationData("LAGaps", "LA Wrath Of God", 0xD6),
    "LA G Rated": LocationData("LAGaps", "LA G Rated", 0xD7),
    "LA Grass Jump": LocationData("LAGaps", "LA Grass Jump", 0xD8),
    "LA Satisfying": LocationData("LAGaps", "LA Satisfying", 0xD9),
    "LA Cleared It!": LocationData("LAGaps", "LA Cleared It!", 0xDA),
    "LA Tight Fit": LocationData("LAGaps", "LA Tight Fit", 0xDB),
    "LA No Look Transfer": LocationData("LAGaps", "LA No Look Transfer", 0xDC),
    "LA Hops": LocationData("LAGaps", "LA Hops", 0xDD),
    "LA It Begins": LocationData("LAGaps", "LA It Begins", 0xDE),
    "LA Arise!": LocationData("LAGaps", "LA Arise!", 0xDF),
    "LA Large": LocationData("LAGaps", "LA Large", 0xE0),
    "LA Be Humble": LocationData("LAGaps", "LA Be Humble", 0xE1),
    "LA Elevator Grind!!": LocationData("LAGaps", "LA Elevator Grind!!", 0xE2),
    "LA Dubba Jump": LocationData("LAGaps", "LA Dubba Jump", 0xE3),
    "LA Epic Jump": LocationData("LAGaps", "LA Epic Jump", 0xE4),
    "LA Nice Start": LocationData("LAGaps", "LA Nice Start", 0xE5),
    "LA Good Thinking": LocationData("LAGaps", "LA Good Thinking", 0xE6),
    "LA Two Ways": LocationData("LAGaps", "LA Two Ways", 0xE7),
    "LA One Giant Leap": LocationData("LAGaps", "LA One Giant Leap", 0xE8),
    "LA Around And Down": LocationData("LAGaps", "LA Around And Down", 0xE9),
    "LA Grinding Down The Highway": LocationData("LAGaps", "LA Grinding Down The Highway", 0xEA),
    "LA Moving Up!": LocationData("LAGaps", "LA Moving Up!", 0xEB),
    "LA Get Up There!": LocationData("LAGaps", "LA Get Up There!", 0xEC),
        #Rio Gaps
    "Rio Up And Over": LocationData("RioGaps", "Rio Up And Over", 0xED),
    "Rio Hyper Monkey": LocationData("RioGaps", "Rio Hyper Monkey", 0xEE),
    "Rio Unbelievable": LocationData("RioGaps", "Rio Unbelievable", 0xEF),
    "Rio Overtime": LocationData("RioGaps", "Rio Overtime", 0xF0),
    "Rio Tripletime": LocationData("RioGaps", "Rio Tripletime", 0xF1),
    "Rio Look Alive Out There": LocationData("RioGaps", "Rio Look Alive Out There", 0xF2),
    "Rio Golden Time": LocationData("RioGaps", "Rio Golden Time", 0xF3),
    "Rio It Is No Dream": LocationData("RioGaps", "Rio It Is No Dream", 0xF4),
    "Rio Take The Fall": LocationData("RioGaps", "Rio Take The Fall", 0xF5),
    "Rio The Nod": LocationData("RioGaps", "Rio The Nod", 0xF6),
    "Rio Like Ninja": LocationData("RioGaps", "Rio Like Ninja", 0xF7),
    "Rio Like Bunny": LocationData("RioGaps", "Rio Like Bunny", 0xF8),
    "Rio Salty Jerky": LocationData("RioGaps", "Rio Salty Jerky", 0xF9),
    "Rio Over The Humps": LocationData("RioGaps", "Rio Over The Humps", 0xFA),
    "Rio Round The Bend": LocationData("RioGaps", "Rio Round The Bend", 0xFB),
    "Rio The Skinny": LocationData("RioGaps", "Rio The Skinny", 0xFC),
    "Rio Working Monkey": LocationData("RioGaps", "Rio Working Monkey", 0xFD),
    "Rio J-Po": LocationData("RioGaps", "Rio J-Po", 0xFE),
    "Rio Crack Shot": LocationData("RioGaps", "Rio Crack Shot", 0xFF),
    "Rio Pithy": LocationData("RioGaps", "Rio Pithy", 0x100),
    "Rio Produce The Points": LocationData("RioGaps", "Rio Produce The Points", 0x101),
    "Rio Legendary": LocationData("RioGaps", "Rio Legendary", 0x102),
    "Rio Wall Crawler": LocationData("RioGaps", "Rio Wall Crawler", 0x103),
    "Rio Mind Bender": LocationData("RioGaps", "Rio Mind Bender", 0x104),
    "Rio The Fear": LocationData("RioGaps", "Rio The Fear", 0x105),
    "Rio Need A Gap": LocationData("RioGaps", "Rio Need A Gap", 0x106),
    "Rio Jimkata!": LocationData("RioGaps", "Rio Jimkata!", 0x107),
    "Rio Peeping Tom": LocationData("RioGaps", "Rio Peeping Tom", 0x108),
    "Rio Fast Like Squirrel": LocationData("RioGaps", "Rio Fast Like Squirrel", 0x109),
        #Suburbia Gaps
    "Suburbia Ice The Ice Cream Man": LocationData("SuburbiaGaps", "Suburbia Ice The Ice Cream Man", 0x10A),
    "Suburbia Rear Entry": LocationData("SuburbiaGaps", "Suburbia Rear Entry", 0x10B),
    "Suburbia Backyard Bump": LocationData("SuburbiaGaps", "Suburbia Backyard Bump", 0x10C),
    "Suburbia Trailerpark Transfer (Fence Side)": LocationData("SuburbiaGaps", "Suburbia Trailerpark Transfer (Fence Side)", 0x10D),
    "Suburbia Trailerpark Transfer (Street Side)": LocationData("SuburbiaGaps", "Suburbia Trailerpark Transfer (Street Side)", 0x10E),
    "Suburbia Trailerpark Transfer (Street Farther Down)": LocationData("SuburbiaGaps", "Suburbia Trailerpark Transfer (Street Farther Down)", 0x10F),
    "Suburbia Line Leap": LocationData("SuburbiaGaps", "Suburbia Line Leap", 0x110),
    "Suburbia Hick Hop": LocationData("SuburbiaGaps", "Suburbia Hick Hop", 0x111),
    "Suburbia Perfecting Your Skills": LocationData("SuburbiaGaps", "Suburbia Perfecting Your Skills", 0x112),
    "Suburbia 10 Stair Set": LocationData("SuburbiaGaps", "Suburbia 10 Stair Set", 0x113),
    "Suburbia OMFG!!!": LocationData("SuburbiaGaps", "Suburbia OMFG!!!", 0x114),
    "Suburbia Over The Green Gap": LocationData("SuburbiaGaps", "Suburbia Over The Green Gap", 0x115),
    "Suburbia Trailer Trash": LocationData("SuburbiaGaps", "Suburbia Trailer Trash", 0x116),
    "Suburbia The Weathervane": LocationData("SuburbiaGaps", "Suburbia The Weathervane", 0x117),
    "Suburbia Bart's Gap": LocationData("SuburbiaGaps", "Suburbia Bart's Gap", 0x118),
    "Suburbia Zen Mind": LocationData("SuburbiaGaps", "Suburbia Zen Mind", 0x119),
    "Suburbia Into The Bowl": LocationData("SuburbiaGaps", "Suburbia Into The Bowl", 0x11A),
    "Suburbia Roof Slide": LocationData("SuburbiaGaps", "Suburbia Roof Slide", 0x11B),
    "Suburbia Grind The Line (Construction Site)": LocationData("SuburbiaGaps", "Suburbia Grind The Line (Construction Site)", 0x11C),
    "Suburbia Grind The Line (Pool House)": LocationData("SuburbiaGaps", "Suburbia Grind The Line (Pool House)", 0x11C),
    "Suburbia Welcome To Suburbia": LocationData("SuburbiaGaps", "Suburbia Welcome To Suburbia", 0x11D),
    "Suburbia Alex Likes Grinding": LocationData("SuburbiaGaps", "Suburbia Alex Likes Grinding", 0x11E),
        #Airport Gaps
    "Airport Banana Gap": LocationData("AirportGaps", "Airport Ganana Gap", 0x11F),
    "Airport Flight On Time": LocationData("AirportGaps", "Airport Flight On Time", 0x120),
    "Airport Holy Pop": LocationData("AirportGaps", "Airport Holy Pop", 0x121),
    "Airport Mad Pop": LocationData("AirportGaps", "Airport Mad Pop", 0x122),
    "Airport Block Hoppin": LocationData("AirportGaps", "Airport Block Hoppin", 0x123),
    "Airport Narrow Escape": LocationData("AirportGaps", "Airport Narrow Escape", 0x124),
    "Airport Secret Stash": LocationData("AirportGaps", "Airport Secret Stash", 0x125),
    "Airport Toaster Pop": LocationData("AirportGaps", "Airport Toaster Pop", 0x126),
    "Airport Brace Yo Self": LocationData("AirportGaps", "Airport Brace Yo Self", 0x127),
    "Airport Bye Bye Knees": LocationData("AirportGaps", "Airport Bye Bye Knees", 0x128),
    "Airport Over The Hump": LocationData("AirportGaps", "Airport Over The Hump", 0x129),
    "Airport Lost Luggage": LocationData("AirportGaps", "Airport Lost Luggage", 0x12A),
    "Airport No Refunds": LocationData("AirportGaps", "Airport No Refunds", 0x12B),
    "Airport Bump-N-Grind": LocationData("AirportGaps", "Airport Bump-N-Grind", 0x12C),
    "Airport Easy Grind": LocationData("AirportGaps", "Airport Easy Grind", 0x12D),
    "Airport Monitor Stomp": LocationData("AirportGaps", "Airport Monitor Stomp", 0x12E),
    "Airport Absolute Grind": LocationData("AirportGaps", "Airport Absolute Grind", 0x12F),
    "Airport Remain Calm": LocationData("AirportGaps", "Airport Remain Calm", 0x130),
    "Airport Don't Panic": LocationData("AirportGaps", "Airport Don't Panic", 0x131),
    "Airport Maintain": LocationData("AirportGaps", "Airport Maintain", 0x132),
    "Airport Progress": LocationData("AirportGaps", "Airport Progress", 0x133),
    "Airport Commit": LocationData("AirportGaps", "Airport Commit", 0x134),
    "Airport Hey Get Down": LocationData("AirportGaps", "Airport Hey Get Down", 0x135),
    "Airport No Acro": LocationData("AirportGaps", "Airport No Acro", 0x136),
    "Airport Freaky Flow": LocationData("AirportGaps", "Airport Freaky Flow", 0x137),
    "Airport Room Wrecka": LocationData("AirportGaps", "Airport Room Wrecka", 0x138),
    "Airport Good Control": LocationData("AirportGaps", "Airport Good Control", 0x139),
    "Airport Skate Everything": LocationData("AirportGaps", "Airport Skate Everything", 0x13A),
    "Airport Plane Bash": LocationData("AirportGaps", "Airport Plane Bash", 0x13B),
    "Airport Low End Theory": LocationData("AirportGaps", "Airport Low End Theory", 0x13C),
    "Airport Nice Manny": LocationData("AirportGaps", "Airport Nice Manny", 0x13D),
    "Airport Precision": LocationData("AirportGaps", "Airport Precision", 0x13E),
    "Airport On Point": LocationData("AirportGaps", "Airport On Point", 0x13F),
        #Skater Island Gaps
    "Skater Island Decked Out": LocationData("SkaterIslandGaps", "Skater Island Decked Out", 0x140),
    "Skater Island Channel Gap": LocationData("SkaterIslandGaps", "Skater Island Channel Gap", 0x141),
    "Skater Island Big Mouth": LocationData("SkaterIslandGaps", "Skater Island Big Mouth", 0x142),
    "Skater Island Over And Out": LocationData("SkaterIslandGaps", "Skater Island Over And Out", 0x143),
    "Skater Island Island Hop": LocationData("SkaterIslandGaps", "Skater Island Island Hop", 0x144),
    "Skater Island Hip To Hip": LocationData("SkaterIslandGaps", "Skater Island Hip To Hip", 0x145),
    "Skater Island Doorway Damage": LocationData("SkaterIslandGaps", "Skater Island Doorway Damage", 0x146),
    "Skater Island Roof To Roof Drop": LocationData("SkaterIslandGaps", "Skater Island Roof To Roof Drop", 0x147),
    "Skater Island Big Air": LocationData("SkaterIslandGaps", "Skater Island Big Air", 0x148),
    "Skater Island Easyway": LocationData("SkaterIslandGaps", "Skater Island Easyway", 0x149),
    "Skater Island Mix It Up": LocationData("SkaterIslandGaps", "Skater Island Mix It Up", 0x14A),
    "Skater Island Corner Plunge": LocationData("SkaterIslandGaps", "Skater Island Corner Plunge", 0x14B),
    "Skater Island Giant Transfer": LocationData("SkaterIslandGaps", "Skater Island Giant Transfer", 0x14C),
    "Skater Island Micro Gap": LocationData("SkaterIslandGaps", "Skater Island Micro Gap", 0x14D),
    "Skater Island Platform Air": LocationData("SkaterIslandGaps", "Skater Island Platform Air", 0x14E),
    "Skater Island Over The Rail": LocationData("SkaterIslandGaps", "Skater Island Over The Rail", 0x14F),
    "Skater Island Watch Yer Head": LocationData("SkaterIslandGaps", "Skater Island Watch Yer Head", 0x150),
    "Skater Island Above The Bar": LocationData("SkaterIslandGaps", "Skater Island Above The Bar", 0x151),
    "Skater Island Pyramid Scam": LocationData("SkaterIslandGaps", "Skater Island Pyramid Scam", 0x152),
    "Skater Island No View": LocationData("SkaterIslandGaps", "Skater Island No view", 0x153),
    "Skater Island Come Down": LocationData("SkaterIslandGaps", "Skater Island Come Down", 0x154),
    "Skater Island Thenextlevel": LocationData("SkaterIslandGaps", "Skater Island Thenextlevel", 0x155),
    "Skater Island Bigdipper": LocationData("SkaterIslandGaps", "Skater Island Bigdipper", 0x156),
    "Skater Island Bench Hoppin": LocationData("SkaterIslandGaps", "Skater Island Bench Hoppin", 0x157),
    "Skater Island Bleacher Bash": LocationData("SkaterIslandGaps", "Skater Island Bleacher Bash", 0x158),
    "Skater Island Eagle Eye": LocationData("SkaterIslandGaps", "Skater Island Eagle Eye", 0x159),
    "Skater Island Cola Fix": LocationData("SkaterIslandGaps", "Skater Island Cola Fix", 0x15A),
    "Skater Island Wall Rail": LocationData("SkaterIslandGaps", "Skater Island Wall Rail", 0x15B),
    "Skater Island Nicewoodwork": LocationData("SkaterIslandGaps", "Skater Island Nicewoodwork", 0x15C),
    "Skater Island Live To Skate": LocationData("SkaterIslandGaps", "Skater Island Live To Skate", 0x15D),
    "Skater Island Skate To Live": LocationData("SkaterIslandGaps", "Skater Island Skate To Live", 0x15E),
    "Skater Island Nice Connection": LocationData("SkaterIslandGaps", "Skater Island Nice Connection", 0x15F),
    "Skater Island Overhand Slap": LocationData("SkaterIslandGaps", "Skater Island Overhand Slap", 0x160),
    "Skater Island Destory The Deep End": LocationData("SkaterIslandGaps", "Skater Island Destroy The Deep End", 0x161),
    "Skater Island Sick Style": LocationData("SkaterIslandGaps", "Skater Island Sick Style", 0x162),
        #Canada Gaps
    "Canada Kicker 2 Kicker": LocationData("CanadaGaps", "Canada Kicker 2 Kicker", 0x163),
    "Canada Over The Pool": LocationData("CanadaGaps", "Canada Over The Pool", 0x164),
    "Canada Billboard Gap": LocationData("CanadaGaps", "Canada Billboard Gap", 0x165),
    "Canada Quarterpipe Transfer": LocationData("CanadaGaps", "Canada Quarterpipe Transfer", 0x166),
    "Canada Roof 2 Roof": LocationData("CanadaGaps", "Canada Roof 2 Roof", 0x167),
    "Canada Over The Quarter": LocationData("CanadaGaps", "Canada Over The Quarter", 0x168),
    "Canada Over The Rails": LocationData("CanadaGaps", "Canada Over The Rails", 0x169),
    "Canada Parking Lot Rail Gap": LocationData("CanadaGaps", "Canada Parking Lot Rail Gap", 0x16A),
    "Canada Hell Yea!": LocationData("CanadaGaps", "Canada Hell Yea!", 0x16B),
    "Canada Crazy Fool": LocationData("CanadaGaps", "Canada Crazy Fool", 0x16C),
    "Canada The Tree": LocationData("CanadaGaps", "Canada The Tree", 0x16D),
    "Canada Big Grind Gap": LocationData("CanadaGaps", "Canada Big Grind Gap", 0x16E),
    "Canada Short Hop": LocationData("CanadaGaps", "Canada Short Hop", 0x16F),
        #Tokyo Gaps
    "Tokyo Sushi Zone SF": LocationData("TokyoGaps", "Tokyo Sushi Zone SF", 0x170),
    "Tokyo Nap Gap": LocationData("TokyoGaps", "Tokyo Nap Gap", 0x171),
    "Tokyo Toi Toi": LocationData("TokyoGaps", "Tokyo Toi Toi", 0x172),
    "Tokyo Nigh And Mighty": LocationData("TokyoGaps", "Tokyo Nigh And Mighty", 0x173),
    "Tokyo Gapanese": LocationData("TokyoGaps", "Tokyo Gapanese", 0x174),
    "Tokyo Greasy": LocationData("TokyoGaps", "Tokyo Greasy", 0x175),
    "Tokyo Ramp2Ramp!": LocationData("TokyoGaps", "Tokyo Ramp2Ramp!", 0x176), #Originally Tranny Gap in game
    "Tokyo Heading For AO's": LocationData("TokyoGaps", "Tokyo Heading For AO's", 0x177),
    "Tokyo Super Jet Pilot Go!": LocationData("TokyoGaps", "Tokyo Super Jet Pilot Go1", 0x178),
    "Tokyo Intersteller Space Grind": LocationData("TokyoGaps", "Tokyo Intersteller Space Grind", 0x179),
    "Tokyo Scabby": LocationData("TokyoGaps", "Tokyo Scabby", 0x17A),
    "Tokyo You Got Gap": LocationData("TokyoGaps", "Tokyo You Got Gap", 0x17B),
    "Tokyo Tight": LocationData("TokyoGaps", "Tokyo Tight", 0x17C),
    "Tokyo Booya-Tight": LocationData("TokyoGaps", "Tokyo Booya-Tight", 0x17D),
    "Tokyo Keep It Going": LocationData("TokyoGaps", "Tokyo Keep It Going", 0x17E),
    "Tokyo Gap For Your Effort": LocationData("TokyoGaps", "Tokyo Gap For Your Effort", 0x17F),
    "Tokyo Ape Grind": LocationData("TokyoGaps", "Tokyo Ape Grind", 0x180),
    "Tokyo Through The Hoops": LocationData("TokyoGaps", "Tokyo Through The Hoops", 0x181),
    "Tokyo Melissa's Gap": LocationData("TokyoGaps", "Tokyo Melissa's Gap", 0x182),
    "Tokyo That's What I'm Sayin'": LocationData("TokyoGaps", "Tokyo That's What I'm Sayin", 0x183),
    "Tokyo Kamikaze": LocationData("TokyoGaps", "Tokyo Kamikaze", 0x184),
        #Downhill Gaps
    "Downhill McCrank It": LocationData("DownhillGaps", "Downhill McCrank It", 0x185),
    "Downhill 16 Stair Set": LocationData("DownhillGaps", "Downhill 16 Stair Set", 0x186),
    "Downhill 20 Stair Set": LocationData("DownhillGaps", "Downhill 20 Stair Set", 0x187),
    "Downhill True Skater": LocationData("DownhillGaps", "Downhill True Skater", 0x188),
    "Downhill Just Like Real Life": LocationData("DownhillGaps", "Downhill Just Like Real Life", 0x189),
    "Downhill Peace Be Still": LocationData("DownhillGaps", "Downhill Speace Be Still", 0x18A),
    "Downhill Obvious Yet Difficult": LocationData("DownhillGaps", "Downhill Obvious Yet Difficult", 0x18B)    
}

location_descriptions = {
    "Foundry High Score": "High Score of 10,000 points in Foundry",
    "Foundry Pro Score": "Pro Score of 40,000 points in Foundry",
    "Foundry Sick Score": "Sick Score of 100,000 points in Foundry",
	"Foundry SKATE": "Collect the SKATE letters in Foundry",
	"Foundry Valves": "Unjam the 5 valves in Foundry",
	"Foundry Press": "Activate the press in Foundry",
	"Foundry Cannonball": "Cannonball over the halfpipe in Foundry",
	"Foundry Control Booth": "Grind the control booth at the back of Foundry",
	"Foundry Secret Tape": "Find the secret tape high up in Foundry",
	"Foundry 100 Percent": "All goals, stats, and deck in Foundry",
	"Foundry SP Press": "Stat Point above the press in Foundry",
	"Foundry SP Catwalk": "Stat Point on the left side of the catwalk in Foundry",
	"Foundry SP Back Balcony": "Stat Point above the control booth on the left side of the balcony in Foundry",
	"Foundry SP Right Pipe": "Stat Point on right pipe near start in Foundry",
	"Foundry SP Back Door": "Stat Point by the back door behind the control booth in Foundry",
	"Foundry Deck": "Deck found at center of the catwalks in Foundry",
    "Foundry":
        """
        The group of all items in Foundry, the first level.
		"""
}
